version: "3.7"
services:
  hub:
    build:
      context: .
    env_file:
      - .env
    restart: always
    image: jupyterhub
    container_name: jupyterhub
    networks:
      - jupyterhub-network
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "jupyterhub-data:/data"
    ports:
      - "8000:8000"

volumes:
  jupyterhub-data:

networks:
  jupyterhub-network:
    name: jupyterhub-network
